#!/usr/bin/env perl

use strict;
use warnings;
use lib "/home/yunfeiguo/projects/SeqMule_dev/lib";
use YAML::Tiny;

my $my_yml;

warn "read 1.yml\n";
$my_yml = YAML::Tiny::LoadFile('1.yml');
print $my_yml,"\n";
for my $i(@$my_yml)
{
    warn "prefix:$i->{prefix}\n";
    warn "filetype:$i->{filetype}\n";
    warn "library:$i->{library}\n";
    warn "readgroup:$i->{readgroup}\n";
    warn "platform:$i->{platform}\n";

    if($i->{filetype} eq 'bam')
    {
	warn @{$i->{file}},"\n";

    } elsif($i->{filetype} eq 'fastq')
    {
	for my $fq(@{$i->{file}})
	{
	    warn "fq: @$fq\n";
	}
    }
}

If you want to do somatic variant calling, just use another file.
Any data sets that have same prefixes in both files will be
considered as normal/tumor pairs. When such pairs exist, SeqMule
automatically use somatic calling algorithms.
