#!/usr/bin/env perl

use strict;
use warnings;
use File::Find;

my $down_cmd="git clone --recursive git://github.com/ekg/freebayes.git";
warn "Version?\n";
my $version=<STDIN>;
chomp $version;
my $out="freebayes_$version.tar.gz";
my @cmd;

push @cmd,$down_cmd;
push @cmd,"tar czvf $out freebayes";

!system($_) or die "Failed: $!\n" for (@cmd);
warn "$out done.\n";
