#!/usr/bin/env perl

use strict;
use warnings;

die "Usage: $0 <db_locations>\n" unless @ARGV==1;
my $no=3;

warn "NOTICE: assume URLs from ${no}rd field\n";
warn "NOTICE: only substitute MD5 for GATK resource bundle files.\n";

my $file=shift @ARGV;
my $newfile="$file.new";
open IN,'<',$file or die "Failed to read $file:$!\n";
open OUT,'>',$newfile or die "Failed to write to $newfile: $!\n";

while(<IN>)
{
    s/[\r\n]+$//;
    if (/broadinstitute/)
    {
	my @f=split /\t/;
	@f=@f[$no-1 .. $#f];

	while (@f)
	{
	    my $url=shift @f;
	    my $md5=shift @f;
	    my $filename=shift @f;

	    my $newmd5=`curl $url.md5` or die "Failed to download $url.md5: $!\n";
	    $newmd5=~s/[\r\n]+$//;
	    $newmd5=~s/\s.*$//;

	    s/$md5/$newmd5/;
	}
    }
    print OUT $_,"\n";
}
close IN;
close OUT;

warn "$newfile done.\n";
