#!/usr/bin/env perl

use strict;
use warnings;

my $original="../advanced_config";

#########BOWTIE2################
{
    my $out="bowtie2_gatk.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatklite_variant=0/gatklite_variant=1/;".
    "s/gatklite_realign=0/gatklite_realign=1/;".
    "s/gatklite_recal=0/gatklite_recal=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_gatklite_norealn_norecal.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatklite_variant=0/gatklite_variant=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_gatklite_norecal.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatklite_variant=0/gatklite_variant=1/;".
    "s/gatklite_realign=0/gatklite_realign=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_gatklite_samtools.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatklite_variant=0/gatklite_variant=1/;".
    "s/gatklite_realign=0/gatklite_realign=1/;".
    "s/gatklite_recal=0/gatklite_recal=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;";
    &procOriginal($out,$regex);
}

{
    my $out="bowtie2_gatklite_samtools_varscan.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatklite_variant=0/gatklite_variant=1/;".
    "s/gatklite_realign=0/gatklite_realign=1/;".
    "s/gatklite_recal=0/gatklite_recal=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;".
    "s/varscan=0/varscan=1/;";
    &procOriginal($out,$regex);
}

{
    my $out="bowtie2_samtools.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_freebayes.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/freebayes=0/freebayes=1/;";
    &procOriginal($out,$regex);
}
#{
#    my $out="bowtie2_snver.config";
#    my $regex=
#    "s/bowtie2=0/bowtie2=1/;".
#    "s/snver=0/snver=1/;";
#    &procOriginal($out,$regex);
#}
{
    my $out="bowtie2_gatk_UnifiedGenotyper.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_UnifiedGenotyper=0/gatk_UnifiedGenotyper=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_gatk_UnifiedGenotyper_norealn_norecal.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatk_UnifiedGenotyper=0/gatk_UnifiedGenotyper=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_gatk_UnifiedGenotyper_norecal.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatk_UnifiedGenotyper=0/gatk_UnifiedGenotyper=1/;".
    "s/gatk_realign=0/gatk_realign=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_gatk_HaplotypeCaller.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_HaplotypeCaller=0/gatk_HaplotypeCaller=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_gatk_HaplotypeCaller_norealn_norecal.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatk_HaplotypeCaller=0/gatk_HaplotypeCaller=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_gatk_HaplotypeCaller_norecal.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatk_HaplotypeCaller=0/gatk_HaplotypeCaller=1/;".
    "s/gatk_realign=0/gatk_realign=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_gatk_UnifiedGenotyper_samtools.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_UnifiedGenotyper=0/gatk_UnifiedGenotyper=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_gatk_HaplotypeCaller_samtools.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_HaplotypeCaller=0/gatk_HaplotypeCaller=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;";
    &procOriginal($out,$regex);
}

{
    my $out="bowtie2_gatk_UnifiedGenotyper_samtools_varscan.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_UnifiedGenotyper=0/gatk_UnifiedGenotyper=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;".
    "s/varscan=0/varscan=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bowtie2_gatk_HaplotypeCaller_samtools_varscan.config";
    my $regex=
    "s/bowtie2=0/bowtie2=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_HaplotypeCaller=0/gatk_HaplotypeCaller=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;".
    "s/varscan=0/varscan=1/;";
    &procOriginal($out,$regex);
}
#########BWA-MEM################
{
    my $out="bwa_gatk.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatklite_variant=0/gatklite_variant=1/;".
    "s/gatklite_realign=0/gatklite_realign=1/;".
    "s/gatklite_recal=0/gatklite_recal=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatklite_norealn_norecal.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatklite_variant=0/gatklite_variant=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatklite_norecal.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatklite_variant=0/gatklite_variant=1/;".
    "s/gatklite_realign=0/gatklite_realign=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatklite_samtools.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatklite_variant=0/gatklite_variant=1/;".
    "s/gatklite_realign=0/gatklite_realign=1/;".
    "s/gatklite_recal=0/gatklite_recal=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatklite_samtools_varscan.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatklite_variant=0/gatklite_variant=1/;".
    "s/gatklite_realign=0/gatklite_realign=1/;".
    "s/gatklite_recal=0/gatklite_recal=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;".
    "s/varscan=0/varscan=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_samtools.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_freebayes.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/freebayes=0/freebayes=1/;";
    &procOriginal($out,$regex);
}
#{
#    my $out="bwa_snver.config";
#    my $regex=
#    "s/bwamem=0/bwamem=1/;".
#    "s/snver=0/snver=1/;";
#    &procOriginal($out,$regex);
#}
{
    my $out="bwa_gatk_UnifiedGenotyper.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_UnifiedGenotyper=0/gatk_UnifiedGenotyper=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatk_UnifiedGenotyper_norealn_norecal.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatk_UnifiedGenotyper=0/gatk_UnifiedGenotyper=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatk_UnifiedGenotyper_norecal.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatk_UnifiedGenotyper=0/gatk_UnifiedGenotyper=1/;".
    "s/gatk_realign=0/gatk_realign=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatk_HaplotypeCaller.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_HaplotypeCaller=0/gatk_HaplotypeCaller=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatk_HaplotypeCaller_norealn_norecal.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatk_HaplotypeCaller=0/gatk_HaplotypeCaller=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatk_HaplotypeCaller_norecal.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatk_HaplotypeCaller=0/gatk_HaplotypeCaller=1/;".
    "s/gatk_realign=0/gatk_realign=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatk_UnifiedGenotyper_samtools.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_UnifiedGenotyper=0/gatk_UnifiedGenotyper=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatk_HaplotypeCaller_samtools.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_HaplotypeCaller=0/gatk_HaplotypeCaller=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatk_UnifiedGenotyper_samtools_varscan.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_UnifiedGenotyper=0/gatk_UnifiedGenotyper=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;".
    "s/varscan=0/varscan=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="bwa_gatk_HaplotypeCaller_samtools_varscan.config";
    my $regex=
    "s/bwamem=0/bwamem=1/;".
    "s/gatk_realign=0/gatk_realign=1/;".
    "s/gatk_recal=0/gatk_recal=1/;".
    "s/gatk_HaplotypeCaller=0/gatk_HaplotypeCaller=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;".
    "s/varscan=0/varscan=1/;";
    &procOriginal($out,$regex);
}
##############SOAP##############
{
    my $out="soap_soapsnp.config";
    my $regex=
    "s/soap=0/soap=1/;".
    "s/soapsnp=0/soapsnp=1/;";
    &procOriginal($out,$regex);
}
#####################BWA-backtrack#################
{
    my $out="bwa_backtrack_gatk.config";
    my $regex=
    "s/bwa=0/bwa=1/;".
    "s/gatklite_variant=0/gatklite_variant=1/;".
    "s/gatklite_realign=0/gatklite_realign=1/;".
    "s/gatklite_recal=0/gatklite_recal=1/;";
    &procOriginal($out,$regex);
}
#{
#    my $out="bwa_backtrack_gatklite_samtools.config";
#    my $regex=
#    "s/bwa=0/bwa=1/;".
#    "s/gatklite_variant=0/gatklite_variant=1/;".
#    "s/gatklite_realign=0/gatklite_realign=1/;".
#    "s/gatklite_recal=0/gatklite_recal=1/;".
#    "s/samtools_mpileup=0/samtools_mpileup=1/;";
#    &procOriginal($out,$regex);
#}
#{
#    my $out="bwa_backtrack_gatklite_samtools_varscan.config";
#    my $regex=
#    "s/bwa=0/bwa=1/;".
#    "s/gatklite_variant=0/gatklite_variant=1/;".
#    "s/gatklite_realign=0/gatklite_realign=1/;".
#    "s/gatklite_recal=0/gatklite_recal=1/;".
#    "s/samtools_mpileup=0/samtools_mpileup=1/;".
#    "s/varscan=0/varscan=1/;";
#    &procOriginal($out,$regex);
#}
{
    my $out="bwa_backtrack_samtools.config";
    my $regex=
    "s/bwa=0/bwa=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;";
    &procOriginal($out,$regex);
}
#{
#    my $out="bwa_backtrack_snver.config";
#    my $regex=
#    "s/bwa=0/bwa=1/;".
#    "s/snver=0/snver=1/;";
#    &procOriginal($out,$regex);
#}
#{
#    my $out="bwa_backtrack_freebayes.config";
#    my $regex=
#    "s/bwa=0/bwa=1/;".
#    "s/freebayes=0/freebayes=1/;";
#    &procOriginal($out,$regex);
#}
#{
#    my $out="bwa_backtrack_gatk_HaplotypeCaller.config";
#    my $regex=
#    "s/bwamem=0/bwamem=1/;".
#    "s/gatk_realign=0/gatk_realign=1/;".
#    "s/gatk_recal=0/gatk_recal=1/;".
#    "s/gatk_HaplotypeCaller=0/gatk_HaplotypeCaller=1/;";
#    &procOriginal($out,$regex);
#}
#{
#    my $out="bwa_backtrack_gatk_UnifiedgenoTyper.config";
#    my $regex=
#    "s/bwamem=0/bwamem=1/;".
#    "s/gatk_realign=0/gatk_realign=1/;".
#    "s/gatk_recal=0/gatk_recal=1/;".
#    "s/gatk_UnifiedGenotyper=0/gatk_UnifiedGenotyper=1/;";
#    &procOriginal($out,$regex);
#}
##################BOWTIE1###################
#{
#    my $out="bowtie1_samtools_varscan.config";
#    my $regex=
#    "s/bowtie=0/bowtie=1/;".
#    "s/samtools_mpileup=0/samtools_mpileup=1/;".
#    "s/varscan=0/varscan=1/;";
#    &procOriginal($out,$regex);
#}
{
    my $out="bowtie1_samtools.config";
    my $regex=
    "s/bowtie=0/bowtie=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;";
    &procOriginal($out,$regex);
}
#{
#    my $out="bowtie1_freebayes.config";
#    my $regex=
#    "s/bowtie=0/bowtie=1/;".
#    "s/freebayes=0/freebayes=1/;";
#    &procOriginal($out,$regex);
#}
#{
#    my $out="bowtie1_snver.config";
#    my $regex=
#    "s/bowtie=0/bowtie=1/;".
#    "s/snver=0/snver=1/;";
#    &procOriginal($out,$regex);
#}
####################SNAP#######################3
{
    my $out="snap_freebayes.config";
    my $regex=
    "s/snap=0/snap=1/;".
    "s/o_samtools_mapQ=\\d+/o_samtools_mapQ=20/;".
    "s/freebayes=0/freebayes=1/;";
    &procOriginal($out,$regex);
}
{
    my $out="snap_freebayes_samtools_varscan.config";
    my $regex=
    "s/snap=0/snap=1/;".
    "s/o_samtools_mapQ=\\d+/o_samtools_mapQ=20/;".
    "s/freebayes=0/freebayes=1/;".
    "s/samtools_mpileup=0/samtools_mpileup=1/;".
    "s/varscan=0/varscan=1/;";
    &procOriginal($out,$regex);
}


sub procOriginal
{
    my $out=shift;
    my $regex=shift;

    open IN,'<',$original or die "Can't open $original: $!\n";
    open OUT,'>',$out or die "Can't write to $out: $!\n";

    while (<IN>)
    {
	s/bwa=\s*\d/bwa=0/;
	s/bwamem=\s*\d/bwamem=0/;
	s/bowtie=\s*\d/bowtie=0/;
	s/bowtie2=\s*\d/bowtie2=0/;
	s/gatklite_variant=\s*\d/gatklite_variant=0/;
	s/gatklite_realign=\s*\d/gatklite_realign=0/;
	s/gatklite_recal=\s*\d/gatklite_recal=0/;
	s/samtools_mpileup=\s*\d/samtools_mpileup=0/;
	s/gatk_realign=\s*\d/gatk_realign=0/; 
	s/gatk_recal=\s*\d/gatk_recal=0/;
	s/gatk_UnifiedGenotyper=\s*\d/gatk_UnifiedGenotyper=0/;
	s/gatk_HaplotypeCaller=\s*\d/gatk_HaplotypeCaller=0/;
	s/varscan=\s*\d/varscan=0/;
	s/soapsnp=\s*\d/soapsnp=0/;
	s/freebayes=\s*\d/freebayes=0/;
	s/snver=\s*\d/snver=0/;
	s/snap=\s*\d/snap=0/;
	eval $regex;
	print OUT;
    }

    close IN;
    close OUT;
    warn "$out done\n";
}

=head

1p_fastqc=1 #FastQC for FASTQ file quality assessment (1 enable,0 disable).

2P_bwamem=1 #BWA-MEM, for read length 70bp-1Mbp, default algorithm for initial alignment (1 enable, 0 disable)

2P_bwa=0 #BWA-Backtrack, for read up to 100bp (1 enable, 0 disable)
2P_bowtie2=0 #bowtie2 is an optional program for initial alignment, it supports gapped alignment and some other new features compared with bowtie (1 enable, 0 disable)

2P_bowtie=0 #bowtie is an optional program for initial alignment, it doesn't support gapped alignment (1 enable, 0 disable)

2P_soap=0 #SOAPaligner is an optional program for initial alignment, its results will only be processed by SOAPsnp.


3p_fastqc=1 
4p_picard_markduplicates=1 #use MarkDuplicates from Picard tools to remove duplicates (1 enable, 0 disable, usually enabled)
5Px_samtools_index=1 #use samtools to index duplicate removed BAM files (1 enable, 0 disable, must be enabled) 

6px_gatklite_realign=1 #use GenomeAnalysisTKLite from GATK to generate GATK intervals and then do realignment (1 enable, 0 disable, usually enabled). Invoke GenomeAnalysisTKLite RealignerTargetCreator and IndelRealigner to do realignment
6px_gatk_realign=0 #use GenomeAnalysisTK full version instead.


7px_gatklite_recal=1 #count covariates for base quality recalibration
7px_gatk_recal=0 #use GenomeAnalysisTK full version instead


8p_gatklite_variant=1 #default variant calling algorithm from GATK Lite (UnifiedGenotyper)

8p_gatk_UnifiedGenotyper=0 #variant calling algorithm (UnifiedGenotyper) from GATK full version

8p_gatk_HaplotypeCaller=0 #alternative variant calling algorithm (HaplotypeCaller) from GATK full version


8p_samtools_mpileup=1 #default variant calling algorithm

8p_varscan=0 #optional variant calling algorithm

8p_soapsnp=0 #optional variant calling algorithm

8p_freebayes=0 #optional variant calling algorithm

8p_snver=0 #optional variant calling algorithm

=cut
